export const COINS_PER_DOLLAR = 250;
export const ERROR_MESSAGE = "Oops, that doesn't look like a valid reddit post!";
const BASE_URL = '(https?://)(www\\.|old\\.|new\\.|m\\.)?reddit\\.com';
const BASE_POST_PATH = '(/r/[A-Za-z0-9_]*/comments/[a-z0-9]{6}';
const BASE_COMMENT_PATH = BASE_POST_PATH + '/[a-z0-9_]*/[a-z0-9]{7}';
export const BASE_POST_PATH_REGEX = new RegExp(BASE_POST_PATH + ')');
export const BASE_COMMENT_PATH_REGEX = new RegExp(BASE_COMMENT_PATH + ')');
export const POST_URL_REGEX = new RegExp(BASE_URL + BASE_POST_PATH + ')');
export const COMMENT_URL_REGEX = new RegExp(BASE_URL + BASE_COMMENT_PATH + ')');